name: Go CI/CD Pipeline

# Workflow triggers: push to main or pull request targeting main
on:
  push:
    branches:
      - main  # Change to your main development branch
  pull_request:
    branches:
      - main  # Change to your main development branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Set the appropriate Go version for your project

      # Step 3: Install Go dependencies
      - name: Install dependencies
        run: go mod download

      # Step 4: Run Go tests
      - name: Run Go tests
        run: go test -v ./...

      # Step 5: Build the Go application
      - name: Build application
        run: go build -o app ./...

      # Optional: Add additional checks or deployment steps as needed
